
import "./globals.css";

export const metadata = {
  title: "Memorial Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
