
import Footer from "@/Components/Shared/Footer";
import Navbar from "@/Components/Shared/Navbar";


export const metadata = {
     title: "Memorial Magazine",
     description: "Generated by create next app",
};

export default function RootLayout({ children }) {
     return (
          <html lang="en">
               <body  className={` antialiased`}>
                   <div>
                     <Navbar></Navbar>
                   </div>
               
                    {children}
                    <div>
                         <Footer></Footer>
                    </div>
               </body>
          </html>
     );
}
